module.exports = {
  apps: [
    {
      name: "omazync-web",
      cwd: "/var/www/omazync",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3000",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: "3000",
      },
      max_memory_restart: "750M",
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 5000,
      exp_backoff_restart_delay: 100,
      error_file: "/var/log/pm2/omazync-web-error.log",
      out_file: "/var/log/pm2/omazync-web-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      kill_timeout: 10000,
      wait_ready: false,
    },
    {
      name: "omazync-email-worker",
      cwd: "/var/www/omazync",
      script: "node_modules/tsx/dist/cli.mjs",
      args: "workers/email-sync.worker.ts",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        REDIS_URL: "redis://127.0.0.1:6379",
        EMAIL_SYNC_WORKER_CONCURRENCY: "2",
        EMAIL_SYNC_IMAP_BATCH_SIZE: "100",
      },
      max_memory_restart: "750M",
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 5000,
      exp_backoff_restart_delay: 100,
      error_file: "/var/log/pm2/omazync-email-worker-error.log",
      out_file: "/var/log/pm2/omazync-email-worker-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      kill_timeout: 15000,
      wait_ready: false,
    },
    {
      name: "omazync-contact-worker",
      cwd: "/var/www/omazync",
      script: "node_modules/tsx/dist/cli.mjs",
      args: "workers/contact-extraction.worker.ts",
      instances: 1,
      exec_mode: "fork",
      env: { NODE_ENV: "production", REDIS_URL: "redis://127.0.0.1:6379", CONTACT_EXTRACTION_WORKER_CONCURRENCY: "3" },
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 5000,
      error_file: "/var/log/pm2/omazync-contact-worker-error.log",
      out_file: "/var/log/pm2/omazync-contact-worker-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      kill_timeout: 15000,
    },
    {
      name: "omazync-export-worker",
      cwd: "/var/www/omazync",
      script: "node_modules/tsx/dist/cli.mjs",
      args: "workers/export.worker.ts",
      instances: 1,
      exec_mode: "fork",
      env: { NODE_ENV: "production", REDIS_URL: "redis://127.0.0.1:6379", EXPORT_WORKER_CONCURRENCY: "2" },
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 5000,
      error_file: "/var/log/pm2/omazync-export-worker-error.log",
      out_file: "/var/log/pm2/omazync-export-worker-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      kill_timeout: 15000,
    },
    {
      name: "omazync-marketing-worker",
      cwd: "/var/www/omazync",
      script: "node_modules/tsx/dist/cli.mjs",
      args: "workers/marketing-sync.worker.ts",
      instances: 1,
      exec_mode: "fork",
      env: { NODE_ENV: "production", REDIS_URL: "redis://127.0.0.1:6379", MARKETING_SYNC_WORKER_CONCURRENCY: "2" },
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 5000,
      error_file: "/var/log/pm2/omazync-marketing-worker-error.log",
      out_file: "/var/log/pm2/omazync-marketing-worker-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      kill_timeout: 15000,
    },
    {
      name: "omazync-scheduler",
      cwd: "/var/www/omazync",
      script: "node_modules/tsx/dist/cli.mjs",
      args: "workers/scheduled-sync.worker.ts",
      instances: 1,
      exec_mode: "fork",
      env: { NODE_ENV: "production", REDIS_URL: "redis://127.0.0.1:6379", SCHEDULED_SYNC_WORKER_CONCURRENCY: "1" },
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 5000,
      error_file: "/var/log/pm2/omazync-scheduler-error.log",
      out_file: "/var/log/pm2/omazync-scheduler-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      kill_timeout: 15000,
    },
  ],
};
