module.exports = {
  apps: [
    {
      name: "next-app",
      cwd: "/var/www/omazync",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3000",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: "3000",
      },
      max_memory_restart: "750M",
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 5000,
      exp_backoff_restart_delay: 100,
      error_file: "/var/log/pm2/omazync-error.log",
      out_file: "/var/log/pm2/omazync-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      kill_timeout: 10000,
      wait_ready: false,
    },
    {
      name: "email-sync-worker",
      cwd: "/var/www/omazync",
      script: "node_modules/tsx/dist/cli.mjs",
      args: "workers/email-sync-worker.ts",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        REDIS_URL: "redis://127.0.0.1:6379",
        EMAIL_SYNC_WORKER_CONCURRENCY: "2",
        EMAIL_SYNC_IMAP_BATCH_SIZE: "100",
      },
      max_memory_restart: "750M",
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 5000,
      exp_backoff_restart_delay: 100,
      error_file: "/var/log/pm2/email-sync-worker-error.log",
      out_file: "/var/log/pm2/email-sync-worker-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      kill_timeout: 15000,
      wait_ready: false,
    },
  ],
};
