-- AlterTable
ALTER TABLE `apilog` MODIFY `platform` ENUM('KIT', 'MAILCHIMP', 'BREVO', 'BEEHIIV', 'ACTIVECAMPAIGN', 'CONVERTKIT_LEGACY', 'HUBSPOT', 'MAILERLITE', 'CONSTANT_CONTACT', 'SENDGRID_MARKETING', 'CAMPAIGN_MONITOR', 'ZOHO_CAMPAIGNS') NULL;

-- AlterTable
ALTER TABLE `integrationaccount` MODIFY `platform` ENUM('KIT', 'MAILCHIMP', 'BREVO', 'BEEHIIV', 'ACTIVECAMPAIGN', 'CONVERTKIT_LEGACY', 'HUBSPOT', 'MAILERLITE', 'CONSTANT_CONTACT', 'SENDGRID_MARKETING', 'CAMPAIGN_MONITOR', 'ZOHO_CAMPAIGNS') NOT NULL;

-- AlterTable
ALTER TABLE `syncrun` MODIFY `platform` ENUM('KIT', 'MAILCHIMP', 'BREVO', 'BEEHIIV', 'ACTIVECAMPAIGN', 'CONVERTKIT_LEGACY', 'HUBSPOT', 'MAILERLITE', 'CONSTANT_CONTACT', 'SENDGRID_MARKETING', 'CAMPAIGN_MONITOR', 'ZOHO_CAMPAIGNS') NULL;
